[package]
name = "gryf"
version = "0.1.0"
authors = ["Petr Nevyhoštěný"]
edition = "2018"

[dependencies]
fixedbitset = "0.4"
arbitrary = { version = "1.0", optional = true, default-features = false }
proptest = { version = "1.0", optional = true, default-features = false }

[features]
all = ["arbitrary", "proptest"]
