name: Lint and test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  format:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check

  lint:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          # Pin the compiler version to avoid future breakage from new lints
          toolchain: 1.67.1
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --tests

  test:
    name: Test (${{ matrix.rust }})
    runs-on: ubuntu-latest
    needs: [format, lint]
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
    env:
      # Property-based tests are ignored if not compiled with this --cfg.
      RUSTFLAGS: --cfg proptest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo test
